version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase       # (опціонально) база, яка створиться автоматично
      MYSQL_USER: user                 # (опціонально) користувач
      MYSQL_PASSWORD: userpassword     # (опціонально) пароль користувача
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
